nginx:
  image: andreev/nginx
  ports:
    - "80:80"
  volumes:
    - ~/www:/var/www
    - ./src/nginx/default:/etc/nginx/sites-available/default
  links:
    - php
    - mysql

php:
  image: andreev/php5-fpm-composer:dev
  volumes:
    - ~/www:/var/www
    - ./src/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src/php/php.ini:/etc/php5/fpm/php.ini
    - ./src/php/php.ini:/etc/php5/cli/php.ini
    - ./src/php/start.sh:/var/docker/scripts/start.sh
    - ./src/php/my_id:/var/docker/scripts/my_id
    - ./src/php/home/local-user/:/home/local-user
    - ./../../scripts:/var/docker/common-scripts
  command: "/var/docker/scripts/start.sh"
  environment:
    MY_NAME: "local-user"
    MY_ID: 1000
    HOST_IP: "192.168.0.101"
    HOST_NAMES: "iss-admin test"
    CUSTOM_CMD: ""
    AFTER_SCRIPT_CMD: "/sbin/my_init -- php5-fpm --nodaemonize"
  expose:
    - "9000"
  links:
    - mysql

mysql:
  image: sameersbn/mysql
  volumes:
    - ./../common/src/mysql/var/lib/mysql:/var/lib/mysql
    - ./../common/src/mysql/etc/mysql:/etc/mysql
    - ./../common/src/mysql/dumps:/home
  environment:
   - DB_NAME=mcs
   - DB_USER=root
   - DB_PASS=root
  ports:
    - "33060:3306"
  expose:
    - "3306"

#redis:
#  image: sameersbn/redis
#  volumes:
#   - ./src/redis/var/lib/redis:/var/lib/redis

#gearman:
#  image: andreev/gearmand
#  volumes:
#   - ./../scripts:/home
#   - ./src/gearman/gearmand.conf:/etc/gearmand.conf
#  command: /home/wait.sh
#  environment:
#    WAIT_HOST: mysql
#    WAIT_PORT: 3306
#    WAIT_START_CMD:
#        "gearmand --config-file /etc/gearmand.conf"
#  links:
#    - mysql

#node:
#  image: andreev/node4
#  volumes:
#   - ~/www:/var/www
#   - ./src/node:/home
#  working_dir: /var/www
#  environment:
#    MY_NAME: "local-user"
#    MY_ID: 1000
#    AFTER_SCRIPT_CMD: "/sbin/my_init"
#    NODE_APP_PATH: "/var/www/rereca/common/node-app"
#    NODE_APPS: "notifications product-stats cashflow"
#  ports:
#    - "3000:3000"
#    - "3001:3001"
#    - "3002:3002"
#  command: /home/strong.sh
#  links:
#    - redis
#    - mysql